language: node_js
node_js:
  - '8'
services:
  - mongodb
addons:
  code_climate:
    repo_token: '7fe522f77e84aaafd85feaeca1070c62ba823c5f9869c66c5ff9961e6c538140'
notifications:
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
  - git clone https://github.com/kalisio/kCore.git && cd kCore && yarn install && yarn link && cd .. && yarn link kCore
  - git clone https://github.com/kalisio/kTeam.git && cd kTeam && yarn install && yarn link && yarn link kCore && cd .. && yarn link kTeam
  - git clone https://github.com/kalisio/kNotify.git && cd kNotify && yarn install && yarn link && yarn link kCore && cd .. && yarn link kNotify
  - git clone https://github.com/kalisio/kMap.git && cd kMap && yarn install && yarn link && yarn link kCore && cd .. && yarn link kMap
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
